### ISSUE TITLE
Block Event Bug

### ISSUE THREAD

**Issue by LuciferWPF910** [Magma-Foundation/Magma#3]
### BLOCK EVENT BUG

**Version :** dd991e7-DEV (MC: 1.12.2)

**Bug:**
On this version and I have reason to believe, all 1.12.2 versions. There is a problem with all block events related to modded blocks.
For example, if im checking the on break/place/use/interact/click etc of a modded block, the event will not trigger. Without any errors typically, sometimes you'll get an error in the console, however, this just relates to the failed event trigger that said plugin attempted.
#
You can see this bug most easily with skript. However, it impacts all plugins.

**Comment by SirMathhman** [comment]
Not related.
